# Generated by Django 3.0.4 on 2020-03-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tried', models.IntegerField()),
                ('num_success', models.IntegerField()),
                ('last_ran', models.DateTimeField(blank=True)),
                ('last_failed', models.DateTimeField(blank=True)),
                ('reliability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
