# Generated by Django 3.0.4 on 2020-03-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_time', models.IntegerField()),
                ('target_room', models.IntegerField()),
            ],
        ),
    ]
